package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImmagineMenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmagineMenuAllPropertiesEquals(ImmagineMenu expected, ImmagineMenu actual) {
        assertImmagineMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertImmagineMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmagineMenuAllUpdatablePropertiesEquals(ImmagineMenu expected, ImmagineMenu actual) {
        assertImmagineMenuUpdatableFieldsEquals(expected, actual);
        assertImmagineMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmagineMenuAutoGeneratedPropertiesEquals(ImmagineMenu expected, ImmagineMenu actual) {
        assertThat(actual)
            .as("Verify ImmagineMenu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmagineMenuUpdatableFieldsEquals(ImmagineMenu expected, ImmagineMenu actual) {
        assertThat(actual)
            .as("Verify ImmagineMenu relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getImmagine()).as("check immagine").isEqualTo(expected.getImmagine()))
            .satisfies(a ->
                assertThat(a.getImmagineContentType()).as("check immagine contenty type").isEqualTo(expected.getImmagineContentType())
            )
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImmagineMenuUpdatableRelationshipsEquals(ImmagineMenu expected, ImmagineMenu actual) {
        assertThat(actual)
            .as("Verify ImmagineMenu relationships")
            .satisfies(a -> assertThat(a.getMenu()).as("check menu").isEqualTo(expected.getMenu()));
    }
}
