package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAllPropertiesEquals(Menu expected, Menu actual) {
        assertMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAllUpdatablePropertiesEquals(Menu expected, Menu actual) {
        assertMenuUpdatableFieldsEquals(expected, actual);
        assertMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAutoGeneratedPropertiesEquals(Menu expected, Menu actual) {
        assertThat(actual)
            .as("Verify Menu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuUpdatableFieldsEquals(Menu expected, Menu actual) {
        assertThat(actual)
            .as("Verify Menu relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()))
            .satisfies(a -> assertThat(a.getAttivo()).as("check attivo").isEqualTo(expected.getAttivo()))
            .satisfies(a -> assertThat(a.getTemplateStyle()).as("check templateStyle").isEqualTo(expected.getTemplateStyle()))
            .satisfies(a -> assertThat(a.getColorePrimario()).as("check colorePrimario").isEqualTo(expected.getColorePrimario()))
            .satisfies(a -> assertThat(a.getColoreSecondario()).as("check coloreSecondario").isEqualTo(expected.getColoreSecondario()))
            .satisfies(a -> assertThat(a.getFontMenu()).as("check fontMenu").isEqualTo(expected.getFontMenu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuUpdatableRelationshipsEquals(Menu expected, Menu actual) {
        // empty method
    }
}
